### ISSUE TITLE
How to use / install this?

### ISSUE THREAD

**Issue by fajaryanw** [SergKolo/xrandr-indicator#3]
please give me explain to install/use this. thanks

**Comment by SergKolo** [comment]
@fajaryanw  Hi ! Are you using Ubuntu ? or any other Linux distribution that uses apt-get ?

**Comment by fajaryanw** [comment]
yes, I've just using Ubuntu 16.04 for 3 months. Sorry, maybe this is a silly question. Thanks for help

**Comment by SergKolo** [comment]
@fajaryanw  OK. I'm making some changes to the code , so once I'm done, I'll add instructions on how to install and use it.  Will let you know in couple days :)

**Comment by SergKolo** [comment]
@fajaryanw  Hi ! I've added the screenshot of how it looks like and instructions on how to install this indicator on the main page of the repository (https://github.com/SergKolo/xrandr-indicator). You can install the indicator via `apt-get` after adding my personal PPA. There's a few other packages in that PPA as well. Hope this helps. Let me know if you have any other questions :)

**Comment by fajaryanw** [comment]
it's work. thank you very much :)
let me know, what's for the "Update menu" ?

**Comment by fajaryanw** [comment]
let me know, what's for the "Update menu" ?

**Comment by SergKolo** [comment]
@fajaryanw  update menu is for when you connnect or disconnect a display, and want to clear the menu.  The indicator doesn't update itself automatically, so if you take out VGA1 display for example, the indicator will still think there's VGA1 attached.
